---
title: "PROJECT 1: Chess Tournament Results: Data extraction and Parsing"
author: "Pascal Hermann Kouogang Tafo"
format: html
editor: visual
---

**INTRODUCTION**

In this project, we will manipulate a structured chess tournament file that contains the result of 64 players. Our goal is to extract some meaningful players data including player's name, state, total tournament points, pre-tournament rating, the average pre-tournament rating of all opponents they faced and then export into a clean, relational CSV file.

**APPROACH**

The text file contains data which are pipe-delimited (`|`) and interleaved across two lines per player. To accomplish my goal, i will take the following steps:

-   Read the file and strip out the dashed separators pairing consecutive player rows.

-   Extract each field of interest (Name, State, Points, and Pre-Rating) using regular expressions and string parsing functions.

-   Create a lookup table because the opponents are listed by "Pair Number" rather than name and perform a second iteration through each player's round results, match their opponents' IDs to their respective Pre-Ratings

-   Compute the rounded mean for the average opponent rating column

-   Export the final results into a clean CSV file
